### ISSUE TITLE
Export resource_id as an output

### ISSUE THREAD

**Issue by jblackburn22** [cloudposse/terraform-aws-rds#111]
## Describe the Feature

Add an output with the [resource_id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#resource_id)

## Expected Behavior

The resource_id is available as an output so it can be used in IAM policy.

## Use Case

I would like to provide EC2 instances and containers to access the RDS instance using RDS IAM authentication and provide access only to a specify RDS instance.  Below is a copy of the [policy](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.IAMPolicy.html)) that I would like to implement.

```
{
   "Version": "2012-10-17",
   "Statement": [
      {
         "Effect": "Allow",
         "Action": [
             "rds-db:connect"
         ],
         "Resource": [
             "arn:aws:rds-db:us-east-2:1234567890:dbuser:db-ABCDEFGHIJKL01234/db_user"
         ]
      }
   ]
}
```

## Alternatives Considered

Otherwise, you need update the IAM policy to use wildcards in the Resource (i.e. arn:aws:rds-db:us-east-2:1234567890:dbuser:*/db_user) specification or add a condition.  These are less secure.

Another alternative would be to convert the RDS instances into RDS Aurora cluster, but this is a bigger effort.

**Comment by nitrocode** [comment]
Looks like it's been added https://github.com/cloudposse/terraform-aws-rds/blob/3b6b1e80156e21a85d9f3943900e6981b9f0d4a5/outputs.tf#L46
