### ISSUE TITLE
Add support for replicate_source_db variable

### ISSUE THREAD

**Issue by adamantike** [cloudposse/terraform-aws-rds#113]
## Describe the Feature

Currently, this module cannot be used to create a read replica, as the [`replicate_source_db`](https://registry.terraform.io/modules/terraform-aws-modules/rds/aws/latest#input_replicate_source_db) variable is not exposed. [cloudposse/terraform-aws-rds-replica](https://github.com/cloudposse/terraform-aws-rds-replica) seems to be the alternative, but hasn't received any updates in over two years.

## Use Case

Using this same module both for creating a RDS primary database, and its read replicas.

## Describe Ideal Solution

Add the [`replicate_source_db`](https://registry.terraform.io/modules/terraform-aws-modules/rds/aws/latest#input_replicate_source_db) variable in this module, and consider if there are variables that only must be provided to the `aws_db_instance` resource when this option is used.

## Alternatives Considered

[cloudposse/terraform-aws-rds-replica](https://github.com/cloudposse/terraform-aws-rds-replica) seems to be the alternative module provided by CloudPosse, but hasn't received any updates in over two years.

**Comment by nitrocode** [comment]
@adamantike have you been able to use the other module to create a read replica ?

If we add `replicate_source_db` variable to this module (and other inputs when this is used), would that not render the other module obsolete ?

**Comment by adamantike** [comment]
@nitrocode, I think it will! However, that module hasn't been updated in more than two years, so it makes sense to either update it with all the same feature this module currently provides (plus, support for newer Terraform versions), or centralize both functionalities here.

As stated in [`aws_db_instance` docs][https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance]:
> NOTE: Removing the replicate_source_db attribute from an existing RDS Replicate database managed by Terraform will promote the database to a fully standalone database.

So, promoting replicas would be simpler just by using the same module, and not requiring Terraform state reimporting.
