### ISSUE TITLE
Creating RDS in newer regions errors but RDS is created

### ISSUE THREAD

**Issue by ktw717** [cloudposse/terraform-aws-rds#114]
## Describe the Bug
Creating RDS in newer regions errors but RDS is still created. 

## Expected Behavior
Either the terraform to error and the RDS to not be created or the terraform to give a warning and the RDS to be created.

## Steps to Reproduce
Create an RDS in a newer region (Confirmed to happen on `me-south1` , `eu-south-1` )

Example: 
```
module "rds_instance" {
  source            = "git::https://github.com/cloudposse/terraform-aws-rds.git?ref=tags/0.35.1"
  enabled           = true
  storage_type      = "gp2"                             # Not req but default to magnetic otherwise
  engine            = "postgres"                        # req
  allocated_storage = 100                               # req
  database_name     = var.database_name                 # req
  database_user     = var.database_user                 # req
  database_password = random_password.pg_passwd.result  # req
  database_port     = 5432                              # req
  multi_az          = false                             # Not req, here for possible future use
  vpc_id            = module.vpc.vpc_id                 # req
  subnet_ids        = module.subnets.private_subnet_ids # req
  storage_encrypted = true                              # Not req but default to false otherwise
  snapshot_identifier = null

  engine_version     = var.engine_version    
  db_parameter_group = var.db_parameter_group
  instance_class     = var.instance_class     # req

  apply_immediately       = false
  maintenance_window      = "Mon:03:00-Mon:04:00"
  skip_final_snapshot     = true
  backup_retention_period = 7
  backup_window           = "22:00-03:00"

  attributes = ["psql"]
  context    = module.label.context
}
```
The error: 

```╷
│ Error: error modifying DB Instance (foo-bar-db-469034-psql): CertificateNotFound: Certificate not found: rds-ca-2019
│       status code: 404, request id: c1b5bac9-b9e1-4243-a747-33a48b408cbd
│ 
│   with module.rds_instance.aws_db_instance.default[0],
│   on .terraform/modules/rds_instance/main.tf line 22, in resource "aws_db_instance" "default":
│   22: resource "aws_db_instance" "default" {
│ 
```

But it has created the db with the default cert.

![image](https://user-images.githubusercontent.com/19327709/118512349-9f0ef880-b72a-11eb-8f0a-062fd4784b8c.png)

The module either needs to use the right default cert so it does not error, or as it is using the default in the end not error out the deployment

**Comment by Karl-Webster** [comment]
Here are the cert names for the regions:

| AWS Region | RDS CA Cert Name       |
|------------|------------------------|
| eu-south-1 | rds-ca-2019-eu-south-1 |
| ap-east-1  | rds-ap-east-1-ca-2019  |
| me-south-1 | rds-ca-2019-me-south-1 |
| af-south-1 | rds-ca-2019-af-south-1 |

**Comment by nnsense** [comment]
Apparently this is yet another `default` value leading to unwanted behaviour. The AWS `aws_db_instance` resource is perfectly able to resolve the CA certificate ID itself, but the module is by default setting `rds-ca-2019` into `variables.tf`  which is not consistent across all the regions. By setting the `ca_cert_identifier` var to `null` (leaving the resource to _guess_ the value) the deployment completes successfully across all regions I've tried. I'm creating a PR to change that default value.

**Comment by nitrocode** [comment]
The `ca_cert_identifier` is defaulted to `null` so this should no longer be an issue.
