### ISSUE TITLE
No documentation for aurora mysql 8 serverless

### ISSUE THREAD

**Issue by jacobnollette** [cloudposse/terraform-aws-rds#152]
Having issues finding out what the cluster family should be for mysql 8 aurora? Any ideas?

**Comment by haidargit** [comment]
Hi,
run this one-liner aws cli command on your terminal/shell to get the cluster families.

`aws rds describe-db-engine-versions --query "DBEngineVersions[].DBParameterGroupFamily" --region <your_region> | grep mysql`

you'll get a long list from the output
```
[
    "aurora-mysql5.7",
    . . .
    "docdb3.6",
    . . .
    "custom-sqlserver-ee-15.0",
    . . .
    . . .
    . . .
    "db2-se-11.5",
    . . .
    etc
]
```

Then choose the desired family based on your needs/requirements.  So this is not a bug, actually.
good luck!

reference: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithDBInstanceParamGroups.html

**Comment by joe-niland** [comment]
Thanks for the info @haidargit
