### ISSUE TITLE
gp3 storage type also supports providing iops manually when storage is atleast 400gb.

### ISSUE THREAD

**Issue by ankitjethi** [cloudposse/terraform-aws-rds#168]
### Describe the Bug

We created a RDS database with gp3 storage type and then after that on the next terraform apply, it is is changing the iops from 3000 to 0.

### Expected Behavior

it should not change to 0. it should stay at 3000 for storage size under 400gb.
And let us customize IOPS for greater that 400gb.

### Steps to Reproduce

create a gp3 RDS  with less than 400gb storage and then re-run terraform apply.

### Screenshots

<img width="971" alt="Screenshot 2024-01-25 at 7 32 24 PM" src="https://github.com/cloudposse/terraform-aws-rds/assets/153623642/d23f3dec-99e9-4a44-a6f0-eecec2b1289c">

**Comment by kbolino** [comment]
Specifically, the issue here seems to be that the `iops` variable in this module has a default of `0` when it should have a default of `null`. Explicitly setting `iops = null` when calling the module fixes the issue.
