### ISSUE TITLE
dns_zone_id isn't working

### ISSUE THREAD

**Issue by orzarchi** [cloudposse/terraform-aws-rds#19]
```
module.database.module.dns_host_name.aws_route53_record.default: aws_route53_record.default: value of 'count' cannot be computed
```

where `module.database` is my invocation of this module. 

The zone id argument usage was straightforward:
` dns_zone_id                 = "${aws_route53_zone.private.id}"`

**Comment by osterman** [comment]
Read more here: 
* https://docs.cloudposse.com/troubleshooting/terraform-value-of-count-cannot-be-computed/

**Comment by osterman** [comment]
We consider this to be a deficiency of the language and not something that we can fix.
