### ISSUE TITLE
Latest version is broken

### ISSUE THREAD

**Issue by sbuljac** [cloudposse/terraform-aws-rds#23]
The latest version is broken on Terraform v0.11.11 with error:
`Error: module.rds_instance_staging.aws_db_instance.default: vpc_security_group_ids: should be a list`
This line is not expanding into list:
`"${aws_security_group.default.*.id}"`
It seems related to this:
https://github.com/hashicorp/terraform/issues/19924

I know this is not the issue with this module but since lates commit break it maybe you could consider reverting.

**Comment by aknysh** [comment]
@sbuljac  thanks for reporting.
we'll fix it.
please don't use `master` branches in your code, pin to a release (master could change and introduce breaking changes)

Pin to a release like this https://github.com/cloudposse/terraform-aws-rds/blob/master/main.tf#L92

**Comment by sbuljac** [comment]
Yea, I did lock it to 0.4.2 after going through pain with this bug :)

**Comment by aknysh** [comment]
@sbuljac 
addressed in https://github.com/cloudposse/terraform-aws-rds/tree/0.4.4
merged to master
