### ISSUE TITLE
aws_db_instance requires license_model parameter for some engines

### ISSUE THREAD

**Issue by shushry** [cloudposse/terraform-aws-rds#25]
https://www.terraform.io/docs/providers/aws/r/db_instance.html#license_model

The license model param is required for some db engines (oracle, sqlserver) but isn't accounted for in the resource in the module.

This will fail if you use the module to stand up a sqlserver SE instance, for example.

**Comment by osterman** [comment]
@shushry thanks for reporting! If you want to open a PR for this, we'll promptly review. We don't have any customers using SQL Server SE.

**Comment by aknysh** [comment]
addressed in #26
