### ISSUE TITLE
SQL Server EX Edition db_name

### ISSUE THREAD

**Issue by rfvermut** [cloudposse/terraform-aws-rds#28]
```* aws_db_instance.default: Error creating DB Instance: InvalidParameterValue: DBName must be null for engine: sqlserver-ex```

but `database_name` is required

**Comment by lodotek** [comment]
so many bugs :-( I am encountering this issue as well

for SQL Server DBName is not applicable and must be null REF: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html

**Comment by nitrocode** [comment]
Yep, that should be `null`. We're also setting that variable to `null` in `mssql` example.

https://github.com/cloudposse/terraform-aws-rds/blob/master/examples/mssql/fixtures.us-east-2.tfvars
