### ISSUE TITLE
Plans to update to .12 syntax?

### ISSUE THREAD

**Issue by tnielsen2** [cloudposse/terraform-aws-rds#32]
Are there any plans to update to the .12 syntax?

Thanks!

**Comment by lodotek** [comment]
bump

**Comment by lodotek** [comment]
Pretty pretty please can someone help here?  Getting many errors like: 
$ terraform plan

Error: Unsupported argument  on .terraform\modules\rds_instance\main.tf line 62, in resource "aws_db_parameter_group" "default":
  62:   parameter = "${var.db_parameter}"
An argument named "parameter" is not expected here. Did you mean to define a
block of type "parameter"?                                                                                                                                                                                                                                                                         
Error: Unsupported argument
  on .terraform\modules\rds_instance\main.tf line 71, in resource "aws_db_option_group" "default":
  71:   option               = "${var.db_options}"
An argument named "option" is not expected here. Did you mean to define a
block of type "option"?
