### ISSUE TITLE
Output `hostname` does not follow convention of word_word.

### ISSUE THREAD

**Issue by davidjeddy** [cloudposse/terraform-aws-rds#57]
Output `hostname` should be `host_name` to match both the naming convention of the other outputs AND the convention of the inputs.

**Comment by nitrocode** [comment]
It follows the output of the resource `module.dns_host_name.hostname` which is configured here https://github.com/cloudposse/terraform-aws-route53-cluster-hostname/blob/master/outputs.tf#L1

We'd have to change it there before changing it here to keep consistency. However, I don't believe the rename will happen as `hostname` is a surprisingly common phrase that it could be seen as a single word (even tho the `module.dns_host_name` is inconsistent with that - which would be easier to rename than the output itself to maintain backwards compatibility).
