### ISSUE TITLE
Add `charset_name` option

### ISSUE THREAD

**Issue by yariksheptykin** [cloudposse/terraform-aws-rds#70]
## Describe the Feature

RDS module should provide a option for specifying database character set.

## Expected Behavior

Setting `character_set_name` to, for example, `utf8mb4` for `engine_name = "mariadb"` craetes a MariaDB instance with `utf8mb4` charset instead of [`latin1`](https://mariadb.com/kb/en/setting-character-sets-and-collations/).

## Use Case

Pimcore has a [hard requirement](https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/DB_Setup.html#page_Database-Setup) for its datbase to use `utf8mb4`-charset. Inability to set this charset makes this module incompatible with pimcore, which is unfortunate.

## Describe Ideal Solution

Introduce a new optional variable `database_charset` and pass it through to `db_instance` resource as [documented here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#character_set_name)

## Alternatives Considered

One alternative considered is forking this repo and adding the option in a fork. But that's unnecessary code duplication and maintenance. Would be better to add this to the official module.

**Comment by yariksheptykin** [comment]
What do you think about this proposal @Gowiem , @osterman ? I would contribute a PR if this seems reasonable.

**Comment by yariksheptykin** [comment]
It looks like I misread the documentation on [`db_instance#character_set_name`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#character_set_name). It says that character set is only applies to "Oracle and Microsoft SQL". I was expecting this to be applicable to all types of engines.

So passing a value to `character_set_name` will only solve the problem for Oracle and Microsoft SQL types of engine. For the other kinds we need to take a different approach as documented [here](https://forums.aws.amazon.com/message.jspa?messageID=153364#153364). It suggests creating adding custom parameters to the parameter_group as demonstrated in [the terraform documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_parameter_group#example-usage).

Applied to this module it would look like this:

```
module "rds_instance" {
...
    db_parameter = [
      { name  = "character_set_server" value = "utf8" },
      { name  = "collation_server" value = "utf8_general_ci" }
    ]
...
}
```

I tested it with this `db_parameter` settings and it resulted in a pimcore-compatible mariadb10.1 database:
```
  db_parameter = [
    {
      name = "character_set_server"
      value = "utf8mb4"
      apply_method = "immediate"
    },
    {
      name = "collation_server"
      value = "utf8mb4_unicode_ci"
      apply_method = "immediate"
    },
    {
      name = "init_connect"
      value = "SET NAMES utf8mb4"
      apply_method = "immediate"
    },
    {
      name = "lower_case_table_names"
      value = "1"
      apply_method = "pending-reboot"
    }
  ]
```

```sh
SELECT default_character_set_name FROM information_schema.SCHEMATA WHERE schema_name = "pimcore";'
+----------------------------+
| default_character_set_name |
+----------------------------+
| utf8mb4                    |
+----------------------------+
1 row in set (0.02 sec)
```

@Gowiem I am not sure how to proceed with this issue. For users of Oracle and Microsoft SQL (if there are any) adding the `charset_name` option would make sense. Users of other db engines ar already able to define charset via `db_parameter` option. I could provide a more detailed documentation in README on how to achieve that.

What do you think?

**Comment by yariksheptykin** [comment]
@Gowiem , @osterma, could you give me a short feedback if I should continue with PR + README or withdraw the PR completely? Thubs up / down is enough. Don't want to waste your time.

**Comment by Gowiem** [comment]
@yariksheptykin PR looks great. Continue with whatever you have outstanding and we'll get it reviewed. 👍
