### ISSUE TITLE
Doing major engine upgrade fails

### ISSUE THREAD

**Issue by yariksheptykin** [cloudposse/terraform-aws-rds#95]
## Describe the Bug
Unable to do a major upgrade for MariaDB going from 10.1 to 10.2, when using options and parameter groups craeted with this module.

## Expected Behavior

Upgrading from 10.1 to 10.2 is as easy as changing the engine version for mariadb and maybe chaning some engine options.

## Steps to Reproduce

1. Deploy RDS with mariadb v 10.1
2. Upgrade to v 10.2

## Environment (please complete the following information):

Linux, Module version 0.20.0 but the failure should be reproducible with the current version as well.

## Additional Context

The upgrade fails because terraform is unable to replace option and parameter groups used for the engine. Going from 10.1 to 10.2 forces replacement of these resources. When terraform tries to create new ones it fails bause the name of the resource is already taken. Deleting these resources before creating new ones also fails because those are being used by the current RDS instance. So creating new parameter group and option group prior to destroting them is reasonable. The only thin is that the names of these resources have to be unique or at least be a function of engine version to avoid conflicts with existing resources.

Here is a relevant piece of terraform apply:

```
Error: Error deleting DB parameter group: InvalidDBParameterGroupState: One or more database instances are still members of this parameter group pimcore, so the group cannot be deleted
	status code: 400, request id: 1dd13feb-1d8f-4069-abe7-ec675d4c2b18

Error: Error creating DB Option Group: OptionGroupAlreadyExistsFault: An option group named pimcore already exists.
	status code: 400, request id: 68ae8ad0-8881-4c2e-b35c-a849dd855240

```

I did a [workaround](https://github.com/yariksheptykin/terraform-aws-rds/commit/de49dc981afd0a79e869e1dde27c3347d96fecfe) for this issue in my fork for 0.20.0. If you think this approach is reasonable, I could port it to the latest version and create a PR.

**Comment by jamengual** [comment]
can you share the plan when the cluster needed to be recreated when changing to a mayor version?

**Comment by yariksheptykin** [comment]
@jamengual , unfortunately I can't get the exact plan output because the logs are gone by now. I will try to reproduce the issue with the lates module version and post the plan here.

If this helps the plan was approximately this. Terraform decided it wanted to replace 2 resources and update 1. The resources to replace were `aws_db_parameter_group` and `aws_db_option_group`. Terraform forced replacement because their `family` and `major_engine_version` changed. The resource to update was `aws_db_instance`. Its engine version was going to be changed from 10.1 to 10.2.

**Comment by dsyrstad** [comment]
I also encountered this issue and I've been using @yariksheptykin's fork. Any chance you could just raise a PR for this, @yariksheptykin?

**Comment by yariksheptykin** [comment]
That's interesting @dsyrstad . My fork patches v0.22 (with v0.22.1), which is quite old now. Are you experiencing this issue in the latest module version? Or do you want a PR against v0.22?

Also, @jamengual asked for a terraform plan, which I cannot reproduce any more, because I no longer have access to this exact environment. Could you maybe share your terraform plan?

**Comment by dsyrstad** [comment]
@yariksheptykin I encountered this issue in Feb. 2021 when upgrading the RDS engine. That's when I found your fork and used it. I was creating a new RDS instance today and still found this issue open, so I thought I'd revive it. After I posted, I used the latest cloudposse module without any issues, but I haven't attempted an engine version upgrade on it. I'm using Postgres if that matters. Perhaps we can close the issue and reopen it if it occurs again. It would be good if you could at least comment here what your fix was at the time.

**Comment by jamengual** [comment]
ok, I will close the issue for now
